apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-circuit-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki-circuit-client
  template:
    metadata:
      labels:
        app: wiki-circuit-client
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: wiki-circuit-client
        image: linkedmink/wiki-circuit-client
        ports:
        - containerPort: 80
        env:
        - name: APP_SERVER_BASE_URL
          value: "https://wiki-circuit-api.linkedmink.space"

---
apiVersion: v1
kind: Service
metadata:
  name: wiki-circuit-client
spec:
  ports:
  - port: 80
  selector:
    app: wiki-circuit-client
